import Home from './Home'
import Splash from './Splash'
import Profile from './Profile'
import Keranjang from './Keranjang'
import Checkout from './Checkout'
import EditProfile from './EditProfile'
import ChangePassword from './ChangePassword'
import History from './History'
import Login from './Login'
import Register1 from './Register/Register1'
import Midtrans from './Midtrans'
import Find from './Find'
import ServiceDetail from './ServiceDetail'
import PerKGServiceDetail from './PerKGServiceDetail'
import ExpressServiceDetail from './ExpressServiceDetail'
import AddBalanceServiceDetail from './AddBalanceServiceDetail'
import IronServiceDetail from './IronServiceDetail'

export { ServiceDetail, Find, Home, Splash, IronServiceDetail,AddBalanceServiceDetail,ExpressServiceDetail,PerKGServiceDetail, Profile, Keranjang, Checkout, EditProfile, ChangePassword, History, Login, Register1,  Midtrans }